### ISSUE TITLE
How can I make the step a leaf step of the flow?

### ISSUE THREAD

**Issue by kaleem-uet** [nocode-js/sequential-workflow-designer#102]
I want to implement a scenario where a step becomes a leaf step of an **if** ( if, block of sequential-workflow-designer)  statement, and adding more steps to it is not allowed once it's placed in either the true or false branch,

**Comment by b4rtaz** [comment]
Hello @kaleem-uet. Sorry I don't understand. Could you draw a mockup?

**Comment by kaleem-uet** [comment]
> Hello @kaleem-uet. Sorry I don't understand. Could you draw a mockup?

![statment](https://github.com/nocode-js/sequential-workflow-designer/assets/71625133/e1e02a61-40cb-4eb6-8f1d-9f17389cd5dd)

**Comment by kaleem-uet** [comment]
> > Hello @kaleem-uet. Sorry I don't understand. Could you draw a mockup?
> 
> ![statment](https://user-images.githubusercontent.com/71625133/280543410-e1e02a61-40cb-4eb6-8f1d-9f17389cd5dd.png)

By leaf step I means. 
The system will not allow the user to add more steps after it.

**Comment by b4rtaz** [comment]
You can limit adding new steps to the branch in two ways:

* you can add a proper [validation](https://nocode-js.com/docs/sequential-workflow-designer/features/validation) (`if (parentSequence.length > 1) ...`),
* configure the [conditional placeholder](https://nocode-js.com/docs/sequential-workflow-designer/features/conditional-placeholders), check [this demo](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/demos/webpack-pro-app/public/minimal-root-component.html). In the demo you cannot put a new step after the "interrupting icon" step. In your case you probably should have a bit different logic. The conditional placeholder is the feature from the [pro version](https://nocode-js.com/sequential-workflow-designer-pro-pricing).
