### ISSUE TITLE
Convert JSON to Flow

### ISSUE THREAD

**Issue by kaleem-uet** [nocode-js/sequential-workflow-designer#104]
In my scenario, I encounter a situation where I create a flow and proceed to the next page, utilizing JSON data. However, when I navigate back to the flow page, I face the need to reconstruct the flow based on the previously generated JSON. The challenge lies in efficiently converting the stored JSON back into a functional flow.

**Comment by b4rtaz** [comment]
Hello @kaleem-uet! I think you should save somewhere the definition before you navigate to a next page. I could be `localStorage` for example.

**Comment by kaleem-uet** [comment]
I have stored it already in the local storage but how i can load the json to canvas (flow-diagram), starting from an empty page ?

**Comment by b4rtaz** [comment]
```js
const definition = { /* ... */ };
Designer.create(placeholder, definition, { /* configuration */ });
```

We have a lot examples how to load the definition at start:
* https://nocode-js.github.io/sequential-workflow-designer/examples/fullscreen.html
* https://nocode-js.github.io/sequential-workflow-designer/examples/live-testing.html

**Comment by kaleem-uet** [comment]
I am using this libray with react js where the definition is:  

`const startDefinition: WorkflowDefinition = {
		type: "root",
		properties: {
		},
		sequence: []
	}`

it  clear the when place createWrite() in the sequence it will create the createWrite() node when the canvas open but i my case 
the local Storage json look like this:
`{
  "type": "root",
  "properties": {},
  "sequence": [
    {
      "id": "4a461004e0b7b9b164d007f784eec730",
      "componentType": "switch",
      "name": "if",
      "properties": {},
      "branches": {
        "true": [],
        "false": []
      }
    }
  ]
}`
and i want to make the flow from this json.

**Comment by b4rtaz** [comment]
> the local stored json look like this:

Yes, and this JSON you should be set to the `startDefinition` variable.

```ts
const [definition, setDefinition] = useState(() => {
    const ls = localStorage['lastState'];
    return ls ? JSON.parse(ls) : { properties: {}, sequence: [] };
});
```

**Comment by kaleem-uet** [comment]
@b4rtaz 
**Thanks 🙏 for the speedy responses and great support – your dedication has made using NoCodeJS a breeze!**
