### ISSUE TITLE
How to add new context menu item?

### ISSUE THREAD

**Issue by nguyendkn** [nocode-js/sequential-workflow-designer#108]
How can I add custom events to the context menu in addition to the default events such as:

- Select
- Delete
- Reset view

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/100742244/b836b70c-fe38-4870-96b3-67856ff75970)

**Comment by b4rtaz** [comment]
Hello @nguyendkn. This is a feature that is coming to the [pro version](https://nocode-js.com/sequential-workflow-designer-pro-pricing).

**Comment by b4rtaz** [comment]
Hello @nguyendkn! In the new version of the pro package we introduced the `Custom Context Menu Items` feature. Now it's possible to add custom items. You can see a demo that included that feature here: https://nocode-js.com/examples/sequential-workflow-designer-pro/webpack-pro-app/public/popup-editor.html

[Here](https://nocode-js.com/docs/sequential-workflow-designer/features/context-menu#custom-context-menu-items) is the documentation (only for clients of the pro package).
