### ISSUE TITLE
Expose walker publicly on Designer

### ISSUE THREAD

**Issue by goldsam** [nocode-js/sequential-workflow-designer#109]
The only way i see to easily query a `Definition` is to manually create an instance of `DefinitionWalker` to use.  It seems like it would be more appropriate to use the `walker` property of `Designer`,  but it is private. 

https://github.com/nocode-js/sequential-workflow-designer/blob/41549b6a009f0e38dc0f572c5aff9556da32586f/designer/src/designer.ts#L81-L87

This instance seems to be the source of "truth" for the rules to visiting/querying a definition. Would you consider changing `walker` to be a public property?

**Comment by b4rtaz** [comment]
Hello @goldsam! Thanks for reporting. Basically you can use the `DefinitionWalker` class by creating an own instance.

```ts
import { DefinitionWalker } from 'sequential-workflow-model';
const walker = new DefinitionWalker();
```

Check [this article](https://nocode-js.com/docs/sequential-workflow-designer/tree-traversal).

But your idea I think may be helpfull for vanilla JavaScript applications, so please check the [0.18.1](https://github.com/nocode-js/sequential-workflow-designer/releases/tag/v0.18.1) version.

```js
designer.getWalker();
```

**Comment by goldsam** [comment]
@b4rtaz Thank you so much for the quick response! That change was very helpful!
