### ISSUE TITLE
Is it possible goto?

### ISSUE THREAD

**Issue by Asif798** [nocode-js/sequential-workflow-designer#11]
![image](https://user-images.githubusercontent.com/95082574/209649454-b6f64fe3-6c7d-417c-9b46-71e1fe1bec42.png)

**Comment by b4rtaz** [comment]
Basically `goto` is considered as [a bad practice](https://stackoverflow.com/questions/3517726/what-is-wrong-with-using-goto). I think it's better to use loops:

```
[loop] condition = if X == Y
|_ [task] X
|_ [task] wait for 1 day(s)
|_ [task] Y
```

If that doesn't solve your problem, currently the designer doesn't have `goto`/`jump` component, but you may use `interruptingTask` or `interruptingIcon` components from [the pro version](https://github.com/nocode-js/sequential-workflow-designer-pro-demo) to present a flow in a more understandable way.

![Goto workflow designer](https://user-images.githubusercontent.com/12797776/209672106-f3efda58-76e3-4761-8727-6a4aaa94a069.png)

Check [this example](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/examples/webpack/public/goto.html).

**Comment by Asif798** [comment]
Hello @b4rtaz 
Thanks for the reply!
