### ISSUE TITLE
Editing Restriction Dynamic Changing

### ISSUE THREAD

**Issue by kaleem-uet** [nocode-js/sequential-workflow-designer#112]
I am encountering an issue with dynamically updating the **stepsConfiguration** prop in the **SequentialWorkflowDesigner** component. It seems that the isDraggable function in the stepsConfiguration doesn't update as expected when the isDrag variable changes.

**Expected Behavior:**
I expect that when the isDrag variable changes, the isDraggable function in the stepsConfiguration prop should dynamically update to reflect the new value.

**My Code** :
```javascript
const [isDrag, setIsDrag] = useState(true);
useEffect(() => {
  // Update isDrag dynamically based on certain conditions
  // However, the SequentialWorkflowDesigner does not reflect this change
  setIsDrag(/* Your updated value based on conditions */);
}, [/* Dependencies */]);

stepsConfiguration: StepsConfiguration = {
  //  ....other configuration 
   isDraggable: () => isDrag,
}

<SequentialWorkflowDesigner
  // Other props...
   stepsConfiguration={stepsConfiguration}
/>
```

**Comment by b4rtaz** [comment]
Hello @kaleem-uet!

The configuration shouldn't be changed after the initialization. You can move the logic to the callback.

```ts
const isDraggable = useRef(true);
const stepsConfiguration = useMemo(() => ({
    isDraggable: () => isDraggable.current
}), []);
```

Then:

```ts
useEffect(() => {
  isDraggable.current = Boolean(/* conditions */);
}, [/* dependencies */]);
```

**Comment by kaleem-uet** [comment]
thanks
