### ISSUE TITLE
I want to zoom to the root node when canvas loads?

### ISSUE THREAD

**Issue by Afrasyabafzal** [nocode-js/sequential-workflow-designer#113]
When i load the canvas you have given a function which move the view port to first step i want to set this to root node

**Comment by b4rtaz** [comment]
Hello @Afrasyabafzal!

The designer supports the [custom viewport](https://nocode-js.com/docs/sequential-workflow-designer/features/custom-viewport) feature in the [pro package](https://nocode-js.com/sequential-workflow-designer-pro-pricing). You can achieve the described behaviour easily.
