### ISSUE TITLE
Can i add restriction to a node so that nobody can place a node above to it?

### ISSUE THREAD

**Issue by Afrasyabafzal** [nocode-js/sequential-workflow-designer#114]

**Comment by b4rtaz** [comment]
Hello @Afrasyabafzal!

Yes, check these articles:
* https://nocode-js.com/docs/sequential-workflow-designer/features/editing-restrictions or
* https://nocode-js.com/docs/sequential-workflow-designer/features/conditional-placeholders (pro).
