### ISSUE TITLE
Force fixed step width

### ISSUE THREAD

**Issue by tskomudek** [nocode-js/sequential-workflow-designer#122]
Hi,

is there any way to force that steps are rendered with a fixed width ?

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/10913215/546cc4d0-8874-4ccf-8f41-fb17493da573)

Thank you

T.

**Comment by b4rtaz** [comment]
Hello @tskomudek!

Check [this article](https://nocode-js.com/docs/sequential-workflow-designer/step-components/task#customization) (the `Customization` fragment), you can override the `minTextWidth` property.

**Comment by tskomudek** [comment]
Hi Bart,

works like a charm, thank you.

T.
