### ISSUE TITLE
Modifier key for moving blocks

### ISSUE THREAD

**Issue by tskomudek** [nocode-js/sequential-workflow-designer#126]
Hi Bart,

with limited space for the designer view, we learned that we often accidentally move blocks(container, switch)  when we want to move the viewport instead. When not switched to readonly, the only option to move the viewport is to zoom out and click into the empty space. But if you zoomed into a larger workflow, you often just want to move the view a bit to continue with configuring the next steps.
A good option would be to move blocks only when a user presses also a modifier key (like ALT, CTRL).

What do you think ?

Also - keyboard shortcuts for moving and zooming would be great.

Tilo

**Comment by b4rtaz** [comment]
Hello @tskomudek!

>  good option would be to move blocks only when a user presses also a modifier key (like ALT, CTRL).

Currently there is an opposite feature, if you click the scroll button of your mouse then you can only move the canvas even if you not enabled "Turn on/off drag and drop" mode.

I like your idea with more keyboard shortcuts. But for the blocking drag&drop I would prefer to keep the consistency with the scroll button. So if you press CTRL, then you cannot drag&drop.

**Comment by tskomudek** [comment]
Hi Bart,

i agree, this would also work for us.
Using the scroll button on the mouse works find btw., but it's not so obvious - so adding the option for an additional key would still be reasonable.

Thank you

Tilo

**Comment by tskomudek** [comment]
Hi Bart,

thanks for taking care of this.
As for the zooming - the external controller interface only allows for zooming in/out, but not to get or set the current zoom level directly. Maybe that's worth adding in a future version.

Best

T.
