### ISSUE TITLE
Loosing zoom level when redrawing

### ISSUE THREAD

**Issue by tskomudek** [nocode-js/sequential-workflow-designer#128]
Hi Bart,

i've created a readonly version of the editor to follow live progress of a workflow,
pretty much like you did in your "live testing" example, but without the move viewport to step feature.

I managed to update step coloring and draw counter badges according to the flows progress.
However, each time the state changes and the react component needs to rerender,
i loose the current zoom level. This can be pretty annoying.

Is there a way to manage the zooming state externally ?

Thanks

Tilo

**Comment by b4rtaz** [comment]
Hello @tskomudek!

If I understand correctly, I think you should use the `SequentialWorkflowDesignerController` class and call the `updateBadges()` method when you want to refresh badges.

```ts
import { useSequentialWorkflowDesignerController } from 'sequential-workflow-designer-react';

const controller = useSequentialWorkflowDesignerController();
// ...
controller.updateBadges();
```

Check "Force Badge Refresh" in [this article](https://nocode-js.com/docs/sequential-workflow-designer/features/badges#force-badge-refresh).

**Comment by tskomudek** [comment]
Hi Bart,

i managed to solve my issue using controller.updateBadges and controller.updateRootComponent.

Thank you

T.
