### ISSUE TITLE
angular limited access

### ISSUE THREAD

**Issue by Mouuus** [nocode-js/sequential-workflow-designer#129]
i want to get the full features from your package like this link: https://nocode-js.github.io/sequential-workflow-designer/examples/live-testing.html
but your provided example in angular doesn't provide it i can only add steps but i can't group or divide them
can i get that?

**Comment by b4rtaz** [comment]
Hello @Mouuus. We don't have the same examples for Vanilla JS/Angular JS/React apps. But all features are available regardless the framework what you use. Check our [documentation](https://nocode-js.com/docs/category/sequential-workflow-designer).

You need to try to adapt the code from Vanilla JS examples to your Angular application, or you can request a feature (in this case "live testing" example for Angular) under paid consulting service.
