### ISSUE TITLE
Method to find out if a task is within a loop block

### ISSUE THREAD

**Issue by raBot1994** [nocode-js/sequential-workflow-designer#131]
HI , is there any out of the box method to find out whether a selected task is a part of a foreach block or not?

If i have the task which is inside an if condition, which is further nested in a looping block, I would still need the method to return true when called, for this task.

**Comment by b4rtaz** [comment]
Hello @raBot1994!

Please check [this article](https://nocode-js.com/docs/sequential-workflow-designer/tree-traversal). By using the `getParents` method you can get all parent steps.
