### ISSUE TITLE
configurable branches number on drop with angular

### ISSUE THREAD

**Issue by Mouuus** [nocode-js/sequential-workflow-designer#132]
is there a way that helps me choose the number of branches for the switch component but this needs to be decided after dropping?
i mean, if the if has two branches by default then when i drop it i can change the number of branches from the step editor? how to do so
or if i can handle the event when drop ends?

**Comment by b4rtaz** [comment]
Hello @Mouuus.

yes, please check [this example](https://nocode-js.github.io/sequential-workflow-designer/examples/multi-conditional-switch.html) (`Parallel step`).

**Comment by Mouuus** [comment]
thank you, but how to achieve that in angular?
