### ISSUE TITLE
Select2 or autocomplete in option fields

### ISSUE THREAD

**Issue by ggparente95** [nocode-js/sequential-workflow-designer#133]
Hi!
I have an options field in the editor, which has more than 50 options. 
I was wondering if is there any chance to set the input as an autocomplete/search field?
Please let me know

Thank you!
Gastón

**Comment by b4rtaz** [comment]
Hello @ggparente95!

You mean the step/root editor? If yes, then the designer has no influence on the appearance of the editor.

Or maybe are you using seuential-workflow-editor?
