### ISSUE TITLE
step direct parent detection in angular

### ISSUE THREAD

**Issue by Mouuus** [nocode-js/sequential-workflow-designer#137]
hello, is there a way to detect a step direct parent? as the getStepParents function doesn't return the desired result 
it returns the same step object

**Comment by b4rtaz** [comment]
The `getStepParents` method returns all parents of a step. So if you have only 1 item in array, your step is in the root sequence. If a step is inside a tree, then you will get an array with all steps above. For example:

```
[loop_step, if_step, 'true', my_step]
```
