### ISSUE TITLE
How can I collapse/expand large sub-trees?

### ISSUE THREAD

**Issue by hchaudhary1** [nocode-js/sequential-workflow-designer#140]
I have large graphs. And I want the users to be able to expand/collapse the sub-graphs so they can remove the extra stuff in their way. 
This is advanced example:
https://reactflow.dev/examples/layout/expand-collapse
But even something simpler/minimal feature such as this above.

I know this is not available in the API/SDK... so can you provide some guidance, on which part of the code can I modify to accomplish this behavior?

**Comment by b4rtaz** [comment]
Hello @hchaudhary1,

have you seen [the folder step component](https://nocode-js.com/docs/sequential-workflow-designer/step-components/folder) in the pro version? Would this solve your problem?

**Comment by hchaudhary1** [comment]
Folder is great to hide things (extra friction to drag and hide... ).. the issue with folder is: how can I quickly un-hide?
Hence, I don't think folder would solve my use-case.

An easy toggle to expand-collapse would be needed... possibly in the context-menu?

**Comment by b4rtaz** [comment]
The [0.21.0](https://github.com/nocode-js/sequential-workflow-designer/releases/tag/v0.21.0) brings the collapsible region feature.
