### ISSUE TITLE
Refresh source / load external source

### ISSUE THREAD

**Issue by MrMoronIV** [nocode-js/sequential-workflow-designer#144]
Is there a way to load/ import a new source while the designer is already created?

So it starts empty and then an import will render the new source with a new undo step? If so, how?

**Comment by b4rtaz** [comment]
Hello @MrMoronIV,

you can use the `replaceDefinition` method. It adds a new definition to the history stack.

```ts
designer.replaceDefinition(newDefinition);
```

**Comment by MrMoronIV** [comment]
That didn't work for some reason, but this did:
`designer.api.editor.definitionModifier.replaceDefinition`

**Comment by b4rtaz** [comment]
The `Designer.replaceDefinition(definition)` method returns the `Promise` instance. Have you used `await`?

Internally it uses the `replaceDefinition` method from the `DefinitionModifier` class. It should work completelly the same.

**Comment by MrMoronIV** [comment]
designer doesn't have a method replaceDefinition, maybe this not latest version doesn't have that method exposed yet.
(I made some small changes for the Ids on the tasks that you now implemented but didn't update yet.)
But it worked out for now. The definition is replaced successfully :)

**Comment by b4rtaz** [comment]
`replaceDefinition` is available from `0.18.4`.

Ok, great!
