### ISSUE TITLE
Update to Angular 17

### ISSUE THREAD

**Issue by mkccl** [nocode-js/sequential-workflow-designer#145]
Hey,
is an update of all dependencies to match Angular 17 in the near future planned?

**Comment by b4rtaz** [comment]
Hello @mkccl!

Could you check the [0.21.1](https://github.com/nocode-js/sequential-workflow-designer/releases/tag/v0.21.1) version?

**Comment by mkccl** [comment]
Oh wow, that was fast. Works ... thanks a lot!
