### ISSUE TITLE
Drag and drop getting stuck

### ISSUE THREAD

**Issue by 889863** [nocode-js/sequential-workflow-designer#149]
Recently started experiencing some issue with Drag and Drop items from Toolbox. It's getting stuck and not able to drag and drop properly. Any suggestions ?

**Comment by b4rtaz** [comment]
You should check the console to see if any error has occurred. Also make sure that all callbacks (`iconUrlProvider`, `isDraggable`...) don't throw unhandled errors.

**Comment by 889863** [comment]
I narrowed down the issue: when hiding sqd-toolbox-item-text and using a full-size icon image, dragging the image doesn't work. I was able to reproduce this problem on your demo page as well.

**Comment by 889863** [comment]
Thanks , so 0.21.2 will fix this issue right ?

**Comment by b4rtaz** [comment]
I think yes. You can also check [any online example](https://nocode-js.github.io/sequential-workflow-designer/examples/fullscreen.html), all examples are now updated to 0.21.2.

**Comment by 889863** [comment]
Perfect .. works fine.
