### ISSUE TITLE
How do I add multiline text for steps ?

### ISSUE THREAD

**Issue by 889863** [nocode-js/sequential-workflow-designer#151]
I would like to add a multiline text for steps and also add custom height for the steps. Is there any way we can achieve this ?

**Comment by b4rtaz** [comment]
Hello @889863,

the pro version offers [Large Task Step Component](https://nocode-js.com/docs/sequential-workflow-designer/step-components/large-task). It allows you to add some description to the component. I'm not sure if the description supports multiline text but it's something worth to consider.

Regarding multi-line names, I'm not sure if this is the correct direction. Names should be short. The toolbox by default doesn't show too long names. More descriptive text can be moved also to the editor. Check [this example](https://nocode-js.com/examples/sequential-workflow-editor-pro/webpack-pro-app/public/editors.html): If you click on any step, you can see a long description at the top of the editor.

Or maybe I don't understand something, can provide a more context?

**Comment by b4rtaz** [comment]
> add custom height

You can customize paddings, distances in each step component, the icon size by providing own configuration. The pro documentation describes how to do it. Currently you can do it only globally (so you cannot have two "task" components with different sizes, but I think this would be a great feature).

**Comment by 889863** [comment]
> Hello @889863,
> 
> the pro version offers [Large Task Step Component](https://nocode-js.com/docs/sequential-workflow-designer/step-components/large-task). It allows you to add some description to the component. I'm not sure if the description supports multiline text but it's something worth to consider.
> 
> Regarding multi-line names, I'm not sure if this is the correct direction. Names should be short. The toolbox by default doesn't show too long names. More descriptive text can be moved also to the editor. Check [this example](https://nocode-js.com/examples/sequential-workflow-editor-pro/webpack-pro-app/public/editors.html): If you click on any step, you can see a long description at the top of the editor.
> 
> Or maybe I don't understand something, can provide a more context?

I actually wanted to show some subtitle for the step .  For example one event is a step and wanted to add Organizer as a subtitle .

**Comment by b4rtaz** [comment]
> I actually wanted to show some subtitle for the step . For example one event is a step and wanted to add Organizer as a subtitle .

It sound like the [Large Task Step Component](https://nocode-js.com/docs/sequential-workflow-designer/step-components/large-task) should fit for your needs. You can also reduce the size of this component (padding, font size etc) if it is too "large" (more details in the pro documentation).

> Do you have any sample code for this ?

If you want to be sure that the pro documentation covers your expectations, you can contact us [here](https://nocode-js.com/contact). [This example](https://nocode-js.com/examples/sequential-workflow-designer-pro/webpack-pro-app/public/custom-theme-flat.html) shows a bit how you can adjust paddings/sizes etc of step components.

**Comment by 889863** [comment]
Looking for some solution for the free version.

**Comment by b4rtaz** [comment]
I understand that, but I cannot share content that is under a paid subscription. These payments for advanced solutions enable this project to offer a free version and essentially exist.
