### ISSUE TITLE
Regarding this app....

### ISSUE THREAD

**Issue by arvidjohansen** [nocode-js/sequential-workflow-designer#152]
I just wanted to say thank you so much..

for taking your time to create open source stuff like this....

.. that makes life easier for the rest of us!

I love this app, it's responsive and intuitive, and not designed for any particular process/backend.

Love that you took your time to make and publish it! (even tho it's javascript! haha jk)

I wish you a lovely day!

Mvh Arvid

**Comment by b4rtaz** [comment]
Thank you @arvidjohansen! :raised_hands:
