### ISSUE TITLE
Safari drag step caused selection on editor

### ISSUE THREAD

**Issue by seanlai** [nocode-js/sequential-workflow-designer#153]
When dragging a step in designer using Safari, the editor part became 'selected' for some reason, causing subsequent drag to be confused as moving selected text on screen. See attached video:

https://github.com/nocode-js/sequential-workflow-designer/assets/3958466/5959fcb6-b7d6-46a8-9a63-2d169a47e93c

I'm on Safari 17.5 and testing with the [live example ](https://nocode-js.github.io/sequential-workflow-designer/examples/live-testing.html)

**Comment by b4rtaz** [comment]
Hello @seanlai, please check the [0.21.3](https://github.com/nocode-js/sequential-workflow-designer/releases/tag/v0.21.3) version.

**Comment by seanlai** [comment]
Fixed! Thanks for the quick response!
