### ISSUE TITLE
🌵 Multi-Conditional Switch Example 

### ISSUE THREAD

**Issue by GhazanfarKhan** [nocode-js/sequential-workflow-designer#161]
Hi, thanks for excellent work.
I need to ask why in this example Condition A and Condition C tasks are connected as show in attached
![image](https://github.com/user-attachments/assets/6f52bfbe-42e8-4d05-a5ab-aae9143e2a78)

**Comment by b4rtaz** [comment]
Hello @GhazanfarKhan,

the chart's design is simplified; essentially, you should interpret it as a flow from top to bottom. Circles with a black border represent inputs, while filled black circles represent outputs. In this case, three outputs converge at the next step, which, in the screenshot, is the final step.
