### ISSUE TITLE
Support for angular 12

### ISSUE THREAD

**Issue by raBot1994** [nocode-js/sequential-workflow-designer#27]
Hi, I am running an existing application with angular 12 and I wish to integrate this with my angular project.

However I see there is some error during compilation stating :

![image](https://user-images.githubusercontent.com/127442378/224163711-8e59146c-795e-4bbd-a65d-ed65fb2472b3.png)

Is there currently no support for angular 12? Or is there any workaround I can use?

Thanks in advance :)

**Comment by b4rtaz** [comment]
I need to check that the `sequential-workflow-designer-angular` package can work with Angular 12. Meanwhile you have 2 options:

1. You may copy [all files from the Angular package](https://github.com/nocode-js/sequential-workflow-designer/tree/main/angular/designer/src) directly into your project (maybe it will work), and use the local version of the component,
2. You can use the base package (`sequential-workflow-designer`): [tutorial](https://nocode-js.com/docs/sequential-workflow-designer/initialize-with-javascript-or-typescript).

**Comment by raBot1994** [comment]
@b4rtaz  - Thanks a ton. Trying out the first approach, will update.

**Comment by raBot1994** [comment]
@b4rtaz is there a way to put in a run / save button to my template file? I don't see it as a property of the base component.

**Comment by b4rtaz** [comment]
>  is there a way to put in a run / save button to my template file?

This is not a responsibility of the designer. You need to track changes independently and save the last version to a variable etc. You can do it by:

```ts
designer.onDefinitionChanged.subscribe((newDefinition) => { /* ... */ });
```

The angular component has a dedicated output for that:

```html
<sqd-designer
  ...
  (onDefinitionChanged)="onDefinitionChanged($event)">
```

**Comment by raBot1994** [comment]
Understood. Thank you for the explanation, much appreciated!

**Comment by raBot1994** [comment]
@b4rtaz do we also have a way to modify the icons of the control-bar , by any chance ? I would like to use different svg icons here. Is that doable?

**Comment by b4rtaz** [comment]
Hi @raBot1994! Please check the `0.9.2` version. It should support Angular 12.
