### ISSUE TITLE
React-Demo Can't resolve 'sequential-workflow-designer' and 'sequential-workflow-designer-react'

### ISSUE THREAD

**Issue by Asif404** [nocode-js/sequential-workflow-designer#30]
I  was trying out the react-demo. 
Cloned repo 
`yarn insall`
`yarn run `
but encoutred this when running.
![Screenshot from 2023-03-16 21-38-54](https://user-images.githubusercontent.com/33574841/225683529-76a516ae-7ee5-4c54-b61e-a98e1599ca34.png)

It seems package is not being installed .

**Comment by Asif404** [comment]
Yes, Sorry i couldn't complete my question.

**Comment by b4rtaz** [comment]
The problem appears because you have cloned the whole repo and the demo is inside the yarn workspace. You need build all packages in the workspace. So go to the root directory:

```
yarn install
yarn build
```

After this you can go to the react demo project and call `yarn start`.

**Comment by b4rtaz** [comment]
Yes, you should take out the `react-app` folder from the yarn workspace.

**Comment by Asif404** [comment]
Great. Thanks
