### ISSUE TITLE
Bug: Step drag&drop doesn't work properly with window scroll

### ISSUE THREAD

**Issue by aharadkou** [nocode-js/sequential-workflow-designer#34]
We're trying to build a bit more complex ui than is shown on demo. Faced with such problem:
![bug-workflow-designer](https://user-images.githubusercontent.com/57901414/230926921-0d723521-d66a-4e58-9ab9-65ec437a5752.gif)

Seems like window scroll offset isn't included in step element position calculation

Package version:
"sequential-workflow-designer": "0.10.0",
"sequential-workflow-designer-react": "0.10.0",

**Comment by b4rtaz** [comment]
Hello @aharadkou! Please check the 0.10.1 version.

**Comment by aharadkou** [comment]
@b4rtaz It works. Thanks for fast fix!
