### ISSUE TITLE
Enhancement: internationalization support

### ISSUE THREAD

**Issue by aharadkou** [nocode-js/sequential-workflow-designer#35]
Is it planned to make static labels as a part of ui component configuration?
![image](https://user-images.githubusercontent.com/57901414/230929432-704655b8-ed47-487e-beb4-70e2a02c0c7d.png)
![image](https://user-images.githubusercontent.com/57901414/230929656-9b5ebc54-ceac-4f08-ace6-736533264dcf.png)

**Comment by b4rtaz** [comment]
Hello @aharadkou. Yes I plan this, but it has a low priority now. The highest priority has features of clients under the consulting service. So if you want to speed up this, please [contact us](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).

**Comment by aharadkou** [comment]
@b4rtaz Clear, thanks
