### ISSUE TITLE
Error while downloading dependencies

### ISSUE THREAD

**Issue by Reza-Noei** [nocode-js/sequential-workflow-designer#39]
Hi, 

I have tried to run below command as documentations said:

`npm i sequential-workflow-designer`

this command failed to below lines: 

> npm WARN deprecated core-js@2.6.4: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

>npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined

>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/reza/.npm/_logs/2023-04-30T22_14_52_723Z-debug-0.log

I have tried to read `debug-0.log` file: 

>7817 http fetch GET 200 https://registry.npmjs.org/eslint/-/eslint-5.12.0.tgz 37068ms (cache miss)
7818 timing reifyNode:node_modules/react-scripts/node_modules/eslint Completed in 39388ms
7819 timing reifyNode:node_modules/react-scripts/node_modules/jsdom Completed in 39571ms
7820 warn deprecated core-js@2.6.4: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
7821 timing reifyNode:node_modules/react-app-polyfill/node_modules/core-js Completed in 46711ms
7822 timing reifyNode:node_modules/react-dev-utils/node_modules/rxjs Completed in 59539ms
7823 timing reifyNode:node_modules/react-scripts/node_modules/rxjs Completed in 59578ms
7824 timing reify:unpack Completed in 59580ms
7825 timing command:audit Completed in 379876ms
7826 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
7826 verbose stack     at validateString (internal/validators.js:120:11)
7826 verbose stack     at relative (path.js:1053:5)
7826 verbose stack     at /usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:1072:21
7826 verbose stack     at Array.map (<anonymous>)
7826 verbose stack     at /usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:1070:66
7826 verbose stack     at Array.map (<anonymous>)
7826 verbose stack     at Arborist.[rollbackMoveBackRetiredUnchanged] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:1070:8)
7826 verbose stack     at Arborist.[reifyPackages] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:234:31)
7826 verbose stack     at async Arborist.reify (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:154:5)
7826 verbose stack     at async Audit.exec (/usr/share/nodejs/npm/lib/commands/audit.js:49:5)
7827 verbose cwd /mnt/d/Workflow/sequential-workflow-designer
7828 verbose Linux 5.10.16.3-microsoft-standard-WSL2
7829 verbose argv "/usr/bin/node" "/usr/bin/npm" "audit" "fix"
7830 verbose node v12.22.9
7831 verbose npm  v8.5.1
7832 error code ERR_INVALID_ARG_TYPE
7833 error The "from" argument must be of type string. Received undefined
7834 verbose exit 1
7835 timing npm Completed in 379990ms
7836 verbose unfinished npm timer reify 1682893087375
7837 verbose unfinished npm timer reify:unretire 1682893272705
7838 verbose code 1
7839 error A complete log of this run can be found in:
7839 error     /home/reza/.npm/_logs/2023-04-30T22_14_52_723Z-debug-0.log

**Comment by b4rtaz** [comment]
Hi @Reza-Noei! Are you sure that this problem is caused by the SWD? The SWD has only [one dependency](https://www.npmjs.com/package/sequential-workflow-designer?activeTab=dependencies): `sequential-workflow-model`. Whereas the `sequential-workflow-model` package has 0 dependencies.

Could you try to install the SWD on an empty project?

**Comment by b4rtaz** [comment]
Due to inactivity, I am closing this thread.
