### ISSUE TITLE
How to display descriptions about a step and can we add our own custom step

### ISSUE THREAD

**Issue by lechuhuuha** [nocode-js/sequential-workflow-designer#46]
Hi i want to add some descriptions for the step using like this image 
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/553d51a7-69fa-49fd-aaa1-23ac0f944c55)

and after drag in the canvas can i still show the descriptions for user to see?
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/44d06f88-cb76-4d56-8218-56476e961d0c)

and lastly can we add our own custom step beside 3 default step?

thanks

**Comment by b4rtaz** [comment]
Hi @lechuhuuha!

> i want to add some descriptions for the step

* Check [large task step](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/demos/webpack-pro-app/public/pro-components.html) in the pro version. It includes a description. 
* Regarding to the toolbox, the default toolbox doesn't support a description but you may [build your custom toolbox](https://nocode-js.com/docs/sequential-workflow-designer/features/external-toolbox) and hide default one.

> can we add our own custom step

Yes, it's possible. We are preparing an article for pro users that describes how to do it.

**Comment by lechuhuuha** [comment]
Thanks manage to work its out.
i had one more question tho

In this example 
https://nocode-js.github.io/sequential-workflow-designer/examples/live-testing.html
Its had the control bar auto appear not need to click on step
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/7cad46a2-6a26-4749-8e19-60f4ae3b90ef)

But in the fullscreen example https://nocode-js.github.io/sequential-workflow-designer/examples/fullscreen.html
I need to click on the step to show the control bar
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/85d70ce9-1999-42ef-9731-078bf7d9f997)

Any idea how this happen ?
Thanks

**Comment by lechuhuuha** [comment]
Thanks i had work its out
