### ISSUE TITLE
Specify the placeholders that can be inserted when the drag step begins.

### ISSUE THREAD

**Issue by lechuhuuha** [nocode-js/sequential-workflow-designer#48]
Hi when begin to drag the step i want to show the user which place they can drop the step to

For example like this image

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/58defda5-faa3-4136-89b0-24cb27eba97b)

Thanks

**Comment by b4rtaz** [comment]
Check [conditional placeholders](https://nocode-js.com/docs/sequential-workflow-designer/features/conditional-placeholders) (available in the pro version). Check [this example](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/demos/webpack-pro-app/public/minimal-root-component.html).

**Comment by lechuhuuha** [comment]
Thanks manage to work its out.
One more thing i want to ask
When adding validation when insert step

I want to make sure only trigger type step in the first position of the sequence
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/5554f22e-4aa4-442f-aa4f-cb6e32a9a2f9)

here is the code in canInsertStep

```js
		canInsertStep: (step, targetSequence, targetIndex) => {
			console.log(
				`step: ${JSON.stringify(step, null, 2)}\n` +
					`targetSequence: ${JSON.stringify(targetSequence, null, 2)}\n` +
					`targetIndex: ${targetIndex}`
			);
			// console.log(designer.api.editor.getDefinition());
			// return true;
			if (!isTriggerStep(step.properties.type) && isStartPosition(targetIndex)) {
				console.error('Can not insert trigger position');
				return false;
			}
			return true;
		}
// here is the additional function
function isTriggerStep(type) {
	if (type == 'trigger') {
		return true;
	}
	return false;
}

function isStartPosition(index) {
	if (index == 0) {
		return true;
	}
	return false;
}
```
I managed to achive its through this code but encounter case when i add switch step then add another step in the yes no branch in the switch step then i can not add any other step because the 3 param step, targetSequence, targetIndex from canInsertStep is the same when the sequence dont have any step

Here is the video

https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/21cf3119-4f6a-42db-a377-854a0d38bb10

Its seem that the switch step is the indepent sequence itself.

Could you help me with this?
Thanks

**Comment by b4rtaz** [comment]
You need to extend your logic by checking if the sequence is the root sequence.

```ts
canInsertStep: (step, targetSequence, targetIndex) => {
  const isRootSequence = designer.getDefinition().sequence === targetSequence;
  // ..
}
```

> Its seem that the switch step is the indepent sequence itself.

The definition of a workflow is a tree, it contains many sequences.

**Comment by lechuhuuha** [comment]
> ```ts
>   const isRootSequence = designer.getDefinition().sequence === targetSequence;
> ```

Thanks but the thing is i want to differentiate between the switch step and the largeTask step
Right now when call
  const isRootSequence = designer.getDefinition().sequence === targetSequence;
  Both of them are true 
  So i can not differentiate between them when do validate canInsertStep
  
  Here is the video describe
  

https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/8bd57e79-a526-4975-a59e-664f625c1ef9

Is there anyway in the canInsertStep or using any other way to only allow the largeTask with properties.type = "trigger" to be in the first position of the tree?

**Comment by b4rtaz** [comment]
You need to join all conditions together.

```ts
canInsertStep: (step, targetSequence, targetIndex) => {
  const isTriggerStep = step.type === 'trigger';
  if (isTriggerStep) {
    const isRootSequence = designer.getDefinition().sequence === targetSequence;
    const isFirstPosition = targetIndex === 0;
    return isRootSequence && isFirstPosition; // the trigger can be placed only at the beginning of the root sequence
  }
  // logic for other steps...
}
```

**Comment by lechuhuuha** [comment]
Manage to work its out
Just post my solution here : 

```js
canInsertStep: (step, targetSequence, targetIndex) => {
			const isTriggerStep = step.properties.type === 'trigger';

			const isTreeEmpty = designer.getDefinition().sequence.length === 0;
			// if tree is empty then only trigger type can insert
			if (isTreeEmpty) {
				if (isTriggerStep) {
					return true;
				} else {
					return false;
				}
			}
			const isTriggerExists = designer.getDefinition().sequence.some(obj => obj.properties.type === 'trigger');

			// action in switch step
			if (!isTreeEmpty && targetSequence.length === 0) {
				return true;
			}

			// try to insert step that is not trigger in trigger position
			if (isTriggerExists && targetSequence.length > 0 && targetIndex === 0) {
				return false;
			}

			return true;
		}
```

and remember to create step with your own custom properties

```js
// you can do the same with any step
function createIfStep(id, name, type, _true, _false) {
	return {
		id,
		componentType: 'switch',
		type: 'if',
		name: name,
		branches: {
			yes: _true,
			no: _false
		},
		properties: {
			draggable: true,
			type: type
		}
	};
}

```
