### ISSUE TITLE
How to customize components？

### ISSUE THREAD

**Issue by ChenRenHu** [nocode-js/sequential-workflow-designer#50]
Is it only supported by the pro version?

**Comment by ChenRenHu** [comment]
in my flow defination, there are many task's  type, like retreive data task , or http task , or send mail task, i think that in my case i need to customize the task' properties to fix different type  properties editor. if  possible , i need to customize the different type task-step's  ui for indicate the task view ;

**Comment by ChenRenHu** [comment]
and i have annother question ,  what's their  relationship (editor, model, designer )

**Comment by b4rtaz** [comment]
The model of a step has two different properties:
* `type` - task type (http task, send mail task, etc),
* `componentType` - component type responsible for rendering a step on canvas.

So you may create multiple steps with the same `componentType`:

```js
{
   type: 'httpTask',
   comonentType: 'task'
   // ...
}
```

```js
{
   type: 'sendMail',
   comonentType: 'task'
   // ...
}
```

In last week we introduced the Sequential Workflow Editor, it helps to solve the problem with building the editor. Check [this demo](https://nocode-js.github.io/sequential-workflow-editor/webpack-app/public/playground.html) ([source code](https://github.com/nocode-js/sequential-workflow-editor/tree/main/demos/webpack-app)).

**Comment by b4rtaz** [comment]
@ChenRenHu did I answer the question? Can we close this issue?

**Comment by ChenRenHu** [comment]
> @ChenRenHu did I answer the question? Can we close this issue?

ok，thx。
