### ISSUE TITLE
How to hide the globar editor on default 

### ISSUE THREAD

**Issue by lechuhuuha** [nocode-js/sequential-workflow-designer#51]
Hi i want to when open the page i can auto hide the global editor 
here is my code 

```js
editors: {
		globalEditorProvider: definition => {
			const root = document.createElement('div');
			root.innerHTML = '<textarea style="width: 100%; border: 0;" rows="50"></textarea>';
			const textarea = root.getElementsByTagName('textarea')[0];
			textarea.value = JSON.stringify(definition, null, 2);
			return root;
		},

		stepEditorProvider: (step, editorContext) => {
			const root = document.createElement('div');
			console.clear();
			// console.log(step.properties)
			console.log(editorContext.notifyPropertiesChanged());
			return root;
		}
	},
```

Is there a way to toggle the global the editor on start

thanks

**Comment by lechuhuuha** [comment]
> Hi! Yeah, this is a missing feature. I have this in the queue. You may increase a priority under a [consulting service](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).

Thanks its a nice feature but i dont need its right now.
Just suggest that tho
Right now i will find the element with the class name and click that element

```js
// Find the div element
			var divElement = document.querySelector('.sqd-smart-editor-toggle.sqd-collapsed');
			
			// Perform the click action
			if (divElement) {
				divElement.click();
			}
```

**Comment by b4rtaz** [comment]
This feature has been added in the [0.13.3](https://github.com/nocode-js/sequential-workflow-designer/releases/tag/v0.13.3) version.

```js
const configuration = {
  editors: {
    isCollapsed: true, // or false
    // ...
  },
  // ...
};

designer.isEditorCollapsed(); // returns true or false
designer.setIsEditorCollapsed(true);
```

**Comment by lechuhuuha** [comment]
nice 
thank you for your hardwork

hope the library continue to grow
