### ISSUE TITLE
Scroll assist

### ISSUE THREAD

**Issue by lechuhuuha** [nocode-js/sequential-workflow-designer#52]
I notice when i have very long workflow then i have to move to the exact position to drop the step

Can we have something like a Scroll assist enable so that when i begin drag the step and move its around then the workflow able to move up,down, left, right 

I can imagine if i move the step to the bottom of the svg then we can move up the workflow and vice versa

Its would be really cool to have that because all the workflow libs i found dont have this fearture

Like in this video

https://github.com/nocode-js/sequential-workflow-designer/assets/59781669/b6d6a547-dbfb-4c8a-bae9-5d80555f4ff8

**Comment by b4rtaz** [comment]
Hi! This is a planned feature. You may increase a priority under a [consulting service](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).

**Comment by raBot1994** [comment]
Hi @b4rtaz is this feature available or is it yet to be released?

**Comment by b4rtaz** [comment]
@raBot1994 it's not available.

**Comment by b4rtaz** [comment]
I'm closing this issue for now.
