### ISSUE TITLE
Parallel Gateway for two or more paths

### ISSUE THREAD

**Issue by cmh234** [nocode-js/sequential-workflow-designer#54]
Hi, very nice application. I want to run some steps in parallel, like a BPMN Gateway instead of a switched choice. Is this possible? Any recommendation?

BPMN Gateway
Decision point that can adjust the path based on conditions or events. They are shown as diamonds. They can be exclusive or inclusive, parallel, complex, or based on data or events.

**Comment by b4rtaz** [comment]
Hello @cmh234!

The designer is not responsible for this part strictly. That depends what a state machine you use. If the state machine supports the parallel execution, you can use the [`switch`](https://nocode-js.com/docs/sequential-workflow-designer/step-components/switch) component for displaying. The `switch` component supports multiple branches and you may set own name for each.

<img width="728" alt="parallel execution BPMN gateway" src="https://github.com/nocode-js/sequential-workflow-designer/assets/12797776/a8cc8f9b-eb9f-4c8d-8cc1-e2c8d205133c">

About a state machine, we provide a solution dedicated to the NodeJS stack: [Sequential Workflow Machine](https://github.com/nocode-js/sequential-workflow-machine). It's very well integrated with the designer, but currently it doesn't support the parallel execution. We may implement this feature under the [consulting service](https://nocode-js.com/sequential-workflow-machine-pro/pricing#consulting).

**Comment by cmh234** [comment]
Thank you for the feedback. Makes sense. I was thinking along the same lines.

**Comment by cmh234** [comment]
What type of data storage do you recommend for these workflows? I'm thinking Mongo Db or Amazon DocumentDB.

 Is the [Sequential Workflow Machine](https://github.com/nocode-js/sequential-workflow-machine) connected to a database?

**Comment by b4rtaz** [comment]
The Sequential Workflow Machine is a library; it is not designed for data storage, but rather for executing predefined workflows.

If you are looking for something integrated with a database please check the [NoCode API Builder Template](https://github.com/nocode-js/nocode-api-builder-template). It uses MongoDB to store workflow definitions. Maybe you could adjust it to your needs.

**Comment by cmh234** [comment]
very interesting thank you
