### ISSUE TITLE
Nested If block restriction

### ISSUE THREAD

**Issue by raBot19** [nocode-js/sequential-workflow-designer#55]
Is there a way to restrict nested if blocks in the designer in angular?

**Comment by raBot19** [comment]
Or atleast any way to know which step is being currently dropped? So i can undo that step if it is a nested if?

**Comment by b4rtaz** [comment]
Hi @raBot19! Check this article: https://nocode-js.com/docs/sequential-workflow-designer/features/editing-restrictions

To use this feature with Angular you need to create a property in your component:

```js
public readonly stepsConfiguration: StepsConfiguration = {
   canInsertStep: () => { /* ... */ },
   // ...
}
```

And pass it to the `sqd-designer`:

```html
<sqd-designer
  ...
  [stepsConfiguration]="stepsConfiguration"></sqd-designer>
```

**Comment by b4rtaz** [comment]
> Is there any release restriction to this feature?

What you mean?

**Comment by raBot19** [comment]
What version of the designer should I be on for this to work ?

**Comment by raBot19** [comment]
Is there also a way for me to get the parent step of a dropped step? 
this.designer.getStepParents(step) returns an error :(

**Comment by raBot19** [comment]
@b4rtaz  having some issues with targetIndex if the conditional block is placed right after a true/false branch. Would help if i could get the right syntax to the getStepParents method.

**Comment by b4rtaz** [comment]
@raBot19 please check this article: https://nocode-js.com/docs/sequential-workflow-designer/tree-traversal

**Comment by raBot19** [comment]
@b4rtaz saw this. I think what's happening here is I'm trying to call this on dragging the step ( canInsertStep method), since the designer change hasn't already happened, getting the parent by the dragged step is returning an error. ( I'm guessing because that step doesn't exist in the definition yet). 

My motive here is to stop the user from dropping a step if it's in a nested conditional block.

**Comment by raBot19** [comment]
I tried the getStepParents method by passing the targetSequence of the canInsertStep method. I'm then checking if the dragged step is of type if. And also checking the returned parent for branches. (Length>=2) 

I would prevent dropping the step if these two conditions satisfy. 

Is there a better way i can do this or something I'm missing here?

**Comment by b4rtaz** [comment]
> I'm guessing because that step doesn't exist in the definition yet

That's correct. The dragging step doesn't have parents. The `getStepParents` method searches the current definition and the dragging step is not added to it yet.

>  I'm then checking if the dragged step is of type if. And also checking the returned parent for branches. (Length>=2)

You should check only parents of the `targetSequence`. If parents contain any specific step type, then you have the answer.

```js
canInsertStep: (step, targetSequence, targetIndex) => {
  const parents = designer.getStepParents(targetSequence);
  const isInLoop = parents.some(s => typeof s === 'object' && s.type === 'loop');
  // ...
```

**Comment by raBot19** [comment]
Got it. 
This really helps. Will try to put this in and get back if I face any hurdles.

**Comment by raBot19** [comment]
@b4rtaz  is there a method to get the parent sequence of a selected step ? i see the stepId present in designer.state.selectedStepId
Is there a way to get the parent sequence for this?

**Comment by raBot19** [comment]
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/126595181/9c8fb8eb-e223-4b25-b604-65a005f95187)


this.designer.getStepParents(editor.step) for RunAnyPostgresQuery

doesnt give me the task above the if condition :(

**Comment by raBot19** [comment]
Is there a method to get the sequence trail for the RunAnyPostgresQuery step? 

As in the steps :
SecurityRemedyTask
Check_Connectivity_of_Server

**Comment by b4rtaz** [comment]
```js
const step = /* ... * /;
const parents = designer.getStepParents(step);
const definition = designer.getDefinition();
let predecessors = [];
let parentSequence = definition.sequence;
for (let i = 0; i < parents.length; i++) {
   const parent = parents[i];
   const offset = parentSequence.indexOf(parent);
   if (offset < 0) {
      throw new Error('Parent not found');
   }
   predecessors = [
      ...predecessors,
      ...parentSequence.slice(0, offset + 1)
   ];
   if (i === parents.length - 1) {
      break;
   }
   if (parent.branches) {
      const branchName = parents[i + 1];
      predecessors.push(branchName);
      parentSequence = parent.branches[branchName];
      i++;
      continue;
   }
   if (parent.sequence) {
      parentSequence = parent.sequence;
      continue;
   }
   throw new Error('Unexpected parent type');
}

console.log(predecessors.map((stepOrName) => typeof stepOrName === 'string' ? stepOrName : stepOrName.name));
```

BTW: please don't change the topic of the issue.

**Comment by raBot19** [comment]
Thanks a ton @b4rtaz !! This serves the purpose. Thanks again :) 

Also wanted to say great work on the designer! We're looking to automate a few processes with it as a front end and it works great :)

**Comment by b4rtaz** [comment]
Thanks!

Is this issue solved?

**Comment by raBot19** [comment]
Yes the snippet you provided serves the purpose but I have to write some more customisations to it to customize it to how we are using the designer. I'm guessing it should work through :) 

Will close the issue and raise another one if there is an issue with traversal! Thanks :)
