### ISSUE TITLE
can i get the undo/redo’s data，then i can reload it when the sequence reload again；

### ISSUE THREAD

**Issue by ChenRenHu** [nocode-js/sequential-workflow-designer#56]

**Comment by b4rtaz** [comment]
> can i get the undo/redo’s data

The stack is not exposed. Why you need it?

> then i can reload it when the sequence reload again

I don't understand this part.

**Comment by ChenRenHu** [comment]
> > can i get the undo/redo’s data
> 
> The stack is not exposed. Why you need it?
> 
> > then i can reload it when the sequence reload again
> 
> I don't understand this part.


when i design my biz sequence，sometime i need save the sequence in tmp archive， the next time i load the tmp archive sequence maybe i undo/redo data ；

**Comment by b4rtaz** [comment]
Hello! This feature is available from the 0.16.4 version. Here is how to use it: https://nocode-js.com/docs/sequential-workflow-designer/features/undo-redo
