### ISSUE TITLE
the controlbar customize & event listen

### ISSUE THREAD

**Issue by ChenRenHu** [nocode-js/sequential-workflow-designer#60]
1.  how can i put an extend control icon into controlbar，and then it can do something else like save action ；
2. an event-listen is in need ，such as the remove control bar， when i use the remove bar for delete a sequence cmp，it can get which cmp had been removed；

**Comment by b4rtaz** [comment]
Hi @ChenRenHu!

1. The control bar doesn't support external buttons, but I like this idea. I will add this feature in the future. You may increase the priority under a [consulting service](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).
2. Basically you may track changes in the definition by listening all changes.

```js
designer.onDefinitionChanged.subscribe((newDef) => { /* ... */);
```

Now you need to compare the previous definition with the current one. Do you need to listen on all changes or only deletion?

**Comment by ChenRenHu** [comment]
1. external control bar button： Is there a way to realize this by modifying the source code?

**Comment by ChenRenHu** [comment]
thx a lot；
