### ISSUE TITLE
Docs are broken 😭 

### ISSUE THREAD

**Issue by paustint** [nocode-js/sequential-workflow-designer#66]
![image](https://github.com/nocode-js/sequential-workflow-designer/assets/5461649/8ed9e235-73a1-430d-b6d8-3a66e213812a)

**Comment by b4rtaz** [comment]
Hello @paustint! Could you share a URL or you are experiencing this problem on the whole website? I cannot reproduce this problem.

**Comment by paustint** [comment]
Seems fine now - but it was the home page https://nocode-js.com/

**Comment by paustint** [comment]
Hit the docs again and seeing the issue. When I hard refresh the error goes away.

Only seems to happen when I click to open the link in a new tab (e.x. right click link in prior post and choose open in a new window

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/5461649/2957b909-aca8-480b-b172-5a3b5ed185fa)

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/5461649/f5c6ca97-a3ce-4d24-9882-dbb25f361ae7)

**Comment by dmx-patrick** [comment]
I was able to reproduce it, the game of life background on the home page crashes when the screen size is too large, making the browser window smaller fixes it.

Canvas size of 2545x1261 crashes.

**Comment by b4rtaz** [comment]
Thanks @paustint for reporting.

Thanks @dmx-patrick for your suggestion. Unfortunately, if I set width=2545 and height=1261 in the code I cannot reproduce the problem. But maybe I've found the problem in the other place. Could you check it now guys?

**Comment by b4rtaz** [comment]
@dmx-patrick nice catch! I've replaced this line by `this.data = nextData;` as you suggested. The changes are deployed, you may check it.

**Comment by dmx-patrick** [comment]
@b4rtaz  no more crash, seems to work fine now.

**Comment by b4rtaz** [comment]
@dmx-patrick thanks for help!
