### ISSUE TITLE
dynamically add or remove available ( predefined ) steps in toolbox.

### ISSUE THREAD

**Issue by Abhishek-Kumbhani** [nocode-js/sequential-workflow-designer#67]
I have recently started exploring the sequential workflow designer, and I want to add it to my React application. In my app, any one step can only be added once, so I want to make that once a step is selected/dropped in the workspace it should be hidden in the toolbox and when I remove it, it should again reappear in the toolbox.

Does anyone know how to do like this,?

**Comment by b4rtaz** [comment]
The built-in toolbox doesn't support that feature. But you may easly implement an own toolbox with this feature.

* Docs: https://nocode-js.com/docs/sequential-workflow-designer/features/external-toolbox
* Example: https://nocode-js.github.io/sequential-workflow-designer-pro-demo/demos/webpack-pro-app/public/external-ui-components.html
