### ISSUE TITLE
Can we have multiple independent flow diagram.

### ISSUE THREAD

**Issue by Abhishek-Kumbhani** [nocode-js/sequential-workflow-designer#68]
How do I add multiple independent flow charts in a single canvas/editor?

**Comment by b4rtaz** [comment]
Hi @Abhishek-Kumbhani! The designer supports only one flow per canvas. If you have a bit more complicated use case, you may attach many designers in one page. Check these examples:

* [Light Dark](https://nocode-js.github.io/sequential-workflow-designer/examples/light-dark.html)
* [Scrollable Page](https://nocode-js.github.io/sequential-workflow-designer/examples/scrollable-page.html)
