### ISSUE TITLE
Is it possible to create a "Stop" step?

### ISSUE THREAD

**Issue by liljefelt** [nocode-js/sequential-workflow-designer#7]
Hi, sorry about posting two issues at once.

I'm wondering how I can create a step that "stops" the flow, ie is not connected to the continued flow?

Something like this
http://46.246.30.230/github/stop-flow.jpg

Thanks!

**Comment by b4rtaz** [comment]
A nice idea! But it's more complicated then the previous issue. For now you can create a "stop" `task`.

```js
const taskStep = {
  componentType: 'task',
  type: 'stop',
  // ...
}
```

If you want to highlight this step from the others you can add some background (check [this example](https://b4rtaz.github.io/sequential-workflow-designer/examples/code-generator.html)).

**Comment by liljefelt** [comment]
I see, yes that workaround is good!

Do you mind explaining in short where the difficulties are?
I would love to take a look myself and see how much I can grasp :)

**Comment by b4rtaz** [comment]
Hi @liljefelt! Currently I'm working on the PRO version. It contains a stoppable task, which I think could fulfill your requirements. If you are interested in the early access of the PRO version please contact with me. You can find the e-mail [here](https://n4no.com/).

<img width="595" alt="Screenshot 2022-12-22 at 23 12 02" src="https://user-images.githubusercontent.com/12797776/209235874-ec951927-b277-49f1-b686-d265e25045b9.png">

**Comment by b4rtaz** [comment]
The interrupting task step is a part of the pro version now. Here you can find [the demo](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/examples/pro-steps/public/).

**Comment by liljefelt** [comment]
Looks awesome!
That said however, since posting this issue I started looking into ReactFlow as an alternative due to the fact that I can leapfrog/circumvent parts of the diagram by just dragging a connecting edge to the place I wish the logic to continue.
