### ISSUE TITLE
Is there a way to highlight a step in the designer without actually selecting the step?

### ISSUE THREAD

**Issue by raBot1994** [nocode-js/sequential-workflow-designer#70]
Is there a method available to highlight a specific task by step id? I dont want it to be selected, i just want the task to be highlighted.

**Comment by b4rtaz** [comment]
Hello @raBot1994! This is a planned feature. So if you want to speed up this, please [contact us](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).

**Comment by raBot1994** [comment]
Thank you @b4rtaz will speak to my team and get back
