### ISSUE TITLE
User defined conditionals?

### ISSUE THREAD

**Issue by gpetrov** [nocode-js/sequential-workflow-designer#71]
Is it possible for the conditional step to have multiple user defined conditions? In our case we need a switch where the user can add its own case choices.

**Comment by gpetrov** [comment]
Thanks! This is very nice but can it be done with an icon next to the existing branches? Like I want to have a [+] visually inside.
Such  "quick actions" might be also useful for other things btw, they might even be multiple or drop a context menu choice.

**Comment by b4rtaz** [comment]
> Like I want to have a [+] visually inside.

This is a planned feature for the pro version. If you want to speed up this, please [contact us](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).

>  Such "quick actions" might be also useful for other things btw, they might even be multiple or drop a context menu choice.

I agree.
