### ISSUE TITLE
public mutation events and pragmatically create actions

### ISSUE THREAD

**Issue by gpetrov** [nocode-js/sequential-workflow-designer#73]
is it possible to listen to mutation events of the workflow designer, like: 
* ready - when flow is is fully rendered
* selected - when a step is selected
* move - when step is moved, with from parents to new parents/position
* delete - when step is deleted
* rename - when title is changed

on the other hand can we pragmatically create new steps or delete/move existing. A public api for this will be very useful

**Comment by b4rtaz** [comment]
Hello @gpetrov!

Check this article: [Sequential Workflow Designer Events](https://nocode-js.com/docs/sequential-workflow-designer/events). The designer already supports several events.

> * move - when step is moved, with from parents to new parents/position
> * delete - when step is deleted
> * rename - when title is changed

To detect these changes you need compare the previous definition and the current definition in the `onDefinitionChanged` event. For now we don't offer any utility to speed up this operation, but this is a planned feature. If you want to speed up this, please [contact us](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).

> on the other hand can we pragmatically create new steps or delete/move existing.

This is possible in several places now:

* you may change step properties and step children by the editor,
* you may change defintiton via the custom action handler (this is available only for pro features).

The designer doesn't support the definition replacement from the outside context for now. But this is a planned feature.
