### ISSUE TITLE
Customization of drop positions and styling

### ISSUE THREAD

**Issue by gpetrov** [nocode-js/sequential-workflow-designer#74]
We really like the sequential workflow designer and it's possibilities but are holded back in usage because of the limited styling and drag and drop UX.

Would it be possible to make the drag and drop more user friendly by not just showing all possible drop areas, which on large actions can be very confusing when you see hundreds of placeholders appearing, to be more consistent like modern drag and drop solutions where a blue line as placeholder appear only when you get in the neighborhood of the element.

So when you hover with your drag on top of step box the blue line appear on top or bottom of the box.

A bit like:

https://spectrum.adobe.com/page/tree-view/#Collapse-and-expand

That will be really a great improvement.

Also styling the connecting lines and giving more options about the besier curves will be great.

And lastly incorporating help or info tooltips per box will be also a great addition to show comments.

**Comment by b4rtaz** [comment]
Hello @gpetrov!

> to be more consistent like modern drag and drop solutions where a blue line as placeholder appear only when you get in the neighborhood of the element.

Now the designer supports basic placeholders and [clickable placeholders](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/demos/webpack-pro-app/public/clickable-placeholder.html). Maybe this is a good candidate for the next type for the pro version.

> Also styling the connecting lines and giving more options about the besier curves will be great.

Currently, it's possible to change the color and the thickness of curves. What you need more?

> And lastly incorporating help or info tooltips per box will be also a great addition to show comments.

I'm not sure if I understand this one correctly. Tooltips in the toolbox, this sounds fine (basically now the designer uses the `title=""` attribute to show the fullname in the toolbox). But I'm afraid, tooltips on the canvas could hide information. Maybe this should work in this way, when a user started dragging, then tooltips are disabled. 🤔

Or maybe it's better to place explanatory information in other places, like editors. Check [this example](https://nocode-js.github.io/sequential-workflow-editor/webpack-app/public/playground.html), here you can find some description at the top of each editor.

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/12797776/ebeab522-3759-40ea-b111-77f7275c0e7d)

------------

Currently we have the full queue of incoming features and primary we focus on features that were ordered under the [consulting service](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting). If you want to prioritize some changes, please contact us.

**Comment by gpetrov** [comment]
> Now the designer supports basic placeholders and [clickable placeholders](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/demos/webpack-pro-app/public/clickable-placeholder.html). Maybe this is a good candidate for the next type for the pro version.
> 

Well the clickable placeholders is a different example but not really the dynamic drop areas that appear only on drag and one at the time

> Currently, it's possible to change the color and the thickness of curves. What you need more?
> 
As I said we really like to customize more the curving 

> I'm not sure if I understand this one correctly. Tooltips in the toolbox, this sounds fine (basically now the designer uses the `title=""` attribute to show the fullname in the toolbox). But I'm afraid, tooltips on the canvas could hide information. Maybe this should work in this way, when a user started dragging, then tooltips are disabled. 🤔

There are different ways to incorporate comments like surrounding boxes with comment lines or additional comment popovers appearing on hover - much more stylable than simple title tag

**Comment by b4rtaz** [comment]
> Well the clickable placeholders is a different example but not really the dynamic drop areas that appear only on drag and one at the time

Yeah, I know it. Just wanted to show that, the designer supports many modes here. That what you suggested, would be the next one.

> As I said we really like to customize more the curving

Probably, I would need some mockup to understand this better.

> There are different ways to incorporate comments like surrounding boxes with comment lines or additional comment popovers appearing on hover - much more stylable than simple title tag

That's right.
