### ISSUE TITLE
Start from a specific step

### ISSUE THREAD

**Issue by velikayikci** [nocode-js/sequential-workflow-designer#77]
Hello, firstly thank you for great product.

How can i start directly from a specific step to execute like below ?

`My code:

    const executeStep = async (step: Step) => {
        const task = taskTypes[step.type];
        await task.execute(step, (sequence: Sequence) => {
            if (sequence?.length) {
                sequence.forEach(async nextStep => {
                    await executeStep(nextStep);
                });
            }
        });
    }

    workflow.sequence.forEach(async (step: Step) => {
        await executeStep(step);
    })`

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/25893525/b30178f2-5bc5-49b5-92e4-05efc92cc682)

**Comment by b4rtaz** [comment]
I would recommend for the execution use the [sequential-workflow-machine](https://github.com/nocode-js/sequential-workflow-machine) package. Internally it uses xstate. Basically the first step is defined in [this file](https://github.com/nocode-js/sequential-workflow-machine/blob/main/machine/src/workflow-machine-builder.ts).

```ts
const machine = createMachine<MachineContext<GlobalState>>({
    initial: 'MAIN',
```

So if you would replace it by:

```ts
initial: getStepNodeId("<step_id>");
```

It should start from that step. For now the package doesn't support any parameter for that, so you need to fork it. If you create an issue in this repo, I'll look at it soon.

BTW: You code has a few problems (for example the `forEach` should be async).

**Comment by velikayikci** [comment]
> I would recommend for the execution use the [sequential-workflow-machine](https://github.com/nocode-js/sequential-workflow-machine) package. Internally it uses xstate. Basically the first step is defined in [this file](https://github.com/nocode-js/sequential-workflow-machine/blob/main/machine/src/workflow-machine-builder.ts).
> 
> ```ts
> const machine = createMachine<MachineContext<GlobalState>>({
>     initial: 'MAIN',
> ```
> 
> So if you would replace it by:
> 
> ```ts
> initial: getStepNodeId("<step_id>");
> ```
> 
> It should start from that step. For now the package doesn't support any parameter for that, so you need to fork it. If you create an issue in this repo, I'll look at it soon.
> 
> BTW: You code has a few problems (for example the `forEach` should be async).

Thank you very much Bart. You are king.

**Comment by velikayikci** [comment]
Hello,

initialStepId does not work for nested states, did you test it ? 
is there and different way ?

**Comment by b4rtaz** [comment]
Hello @velikayikci, the `initialStepId` property is removed. Yes, it didn't work correctly. Could you describe your problem more in detail? Are you looking for the persistent feature or do you need to start the workflow from a specific step for another reason?

**Comment by velikayikci** [comment]
Hello @b4rtaz
Yes, we need to start the workflow from a specific step, not from 'start' step.
Thanks.

**Comment by velikayikci** [comment]
Hello @b4rtaz 
**I use your workflow designer as a BPM designer,** 
in the example below, if the manager approved than that will go to CEO approve and interrupt, 
Than CEO will open for the approve, flow must start from "CEO Approve" step.

That's why we need start a specific step.

![image](https://github.com/user-attachments/assets/ca08fc07-ea1d-4083-a18d-4ed61bda5dd8)

**Comment by b4rtaz** [comment]
I think it would probably be better to use the persistent workflow for this case. It works like this: when the execution reaches the 'CEO Approve' task, the process stops. At this point, you can save the current workflow state, for example, to the database. After the approval, you need to restore the workflow, which will then resume from the previously stopped point.

The Sequential Workflow Machine currently supports only the signal activity, which allows for stopping the execution and resuming it later. This activity is in the experimental stage, so there is no documentation yet (but [this test](https://github.com/nocode-js/sequential-workflow-machine/blob/main/machine/src/activities/signal-activity/signal-activity.spec.ts) may describe how it works through code). You can see some live demo [here](https://visiopilot.com/demos/chat-all-chat-items.html) how it works.

In your case, you need a signaled version of the fork activity. You want to stop the execution until a signal with a decision comes back. This functionality is not currently available.

---

The signal fork activity is something I plan to add to the SWM, but it is currently a low priority. If you would like this feature implemented within a predictable timeframe, please consider our consulting service, where we can expedite the process.

---

By the way, I tried some time ago to fix the `initialStepId` feature, but after a while, I resigned. It seems this is not a trivial problem. Currently, for my needs, the signaled approach completely fulfills all requirements.

**Comment by velikayikci** [comment]
Thank you @b4rtaz for your feedback.

in fact i solve this problem like below, i always start from start node with the history list, do you think this way is ok ?
![image](https://github.com/user-attachments/assets/0e3ddeb0-93d8-4002-9b34-0ca7355d3b63)

**Comment by velikayikci** [comment]
by the way i saw this now, 
https://github.com/jbranchaud/til/blob/master/xstate/start-a-machine-in-a-specific-state.md

**Comment by b4rtaz** [comment]
> in fact i solve this problem like below, i always start from start node with the history list, do you think this way is ok ?

In my opinion, this is not a good solution. It won't work for loops (it would be very hard to determine if the step was executed in some iteration), and the size of this set may increase without limits. This could also lead to spaghetti code.

In my opinion, the persistent feature is the only thing that makes sense here. You should stop the entire workflow with the current state and resume it with the same state. The signaled approach, in my opinion, is the way to go, and it's also battle-tested in VisioPilot.

> by the way this is works for full path of node id

If I remember correctly, I had a solution that worked only for the children of the root sequence, but it didn't work for deeper children. You should check if your approach does not have the same problem.

**Comment by velikayikci** [comment]
Thank you for your feedbacks @b4rtaz

this is works for initialStepId.

```
public start(): this {
    const nodeId = getStepNodeId('ebdc77ce-f278-4c9c-b1f6-c4b40bddc264');
    const node = this.interpreter.machine.getStateNodeById(nodeId);
    const fullPath = node.path.join('.');
    const initialState = this.interpreter.machine.getInitialState(fullPath);
    this.interpreter.start(initialState);
    return this;
}
```

**Comment by b4rtaz** [comment]
Nice! Great job! This definetely is a nice feature for the SWM.
