### ISSUE TITLE
How to know is finished ?

### ISSUE THREAD

**Issue by velikayikci** [nocode-js/sequential-workflow-designer#78]
Hello, how to know is finished ?

`Is this code correct ?

    const machine = builder.build(workflow);
    const interpreter = machine.create({ init: () => state });

    interpreter.onChange(() => { });
    interpreter.onDone(() => {
        const snapshot = interpreter.getSnapshot();
        if (snapshot.statePath.includes('FINISHED')) {
            // correct ?
        }
    });
    interpreter.start();`

![image](https://github.com/nocode-js/sequential-workflow-designer/assets/25893525/3520174b-1bc2-4373-9808-9fdbdae76aa0)

**Comment by b4rtaz** [comment]
```ts
import { STATE_INTERRUPTED_ID } from 'sequential-workflow-machine';

return new Promise((resolve, reject) => {
	interpreter.onDone(() => {
		const snapshot = this.interpreter.getSnapshot();
		if (snapshot.unhandledError) {
			reject(snapshot.unhandledError);
		} else if (snapshot.statePath[0] === STATE_INTERRUPTED_ID) {
			const error = snapshot.globalState.interruptedError ?? new Error('Interrupted');
			reject(error);
		} else {
			resolve();
		}
	});
});
```

**Comment by b4rtaz** [comment]
@velikayikci have this solved your problem?
