### ISSUE TITLE
Cannot use sequential-workflow-designer-react with React 17 and lower

### ISSUE THREAD

**Issue by ant066** [nocode-js/sequential-workflow-designer#79]
**Steps to Reproduce:**
1. Install the package in a project that uses React 17 or lower versions.
2. Import and use the package components in a React component.
3. Attempt to build or run the project.

**Expected Behavior:**
I expect the package to work seamlessly with React 17 and lower versions without encountering any errors related to 'react-dom/client.'

**Actual Behavior:**

```Module not found: Can't resolve 'react-dom/client' in '.../node_modules/sequential-workflow-designer-react/lib/esm'```

The error message mentioned above is preventing me from using the package effectively with React 17 and lower versions.

**Additional Information:**
I have tried the following troubleshooting steps, but the issue persists:
- Checked for the presence of 'react' and 'react-dom' in my project's dependencies.
- Ensured that my webpack configuration is correctly set up to resolve React and ReactDOM.
- Restarted my development server.

Please let me know if there are any specific configurations or changes I can make to resolve this issue, or if an update to the package is needed to support React 17 and lower versions.

Thank you for your assistance.

**Comment by anduongmomos** [comment]
I forked the React repository to this: https://github.com/ant066/sequential-workflow-designer-react. For anyone who wants to use this with React v17, you can install the package `sequential-workflow-designer-react-17`.

**Comment by ant066** [comment]
I forked the React repository to this: https://github.com/ant066/sequential-workflow-designer-react. For anyone who wants to use this with React v17, you can install the package `sequential-workflow-designer-react-17`
