### ISSUE TITLE
Is Horizontal Workflow possible?

### ISSUE THREAD

**Issue by thcristianno** [nocode-js/sequential-workflow-designer#8]
Good morning @b4rtaz , congratulations for your workflow.
I need to work with somewhat extensive flows.
In this case, the view of the processes only vertically will be too large. Would it be possible to add steps in the flow horizontally as well?

Example:
![image](https://user-images.githubusercontent.com/17443896/208651908-f4d56e83-2cfe-48e6-a085-e6793b71c1aa.png)

**Comment by b4rtaz** [comment]
Hi @thcristianno!

Currently I plan to add a feature to reduce a size of a flow. That would be a new step called "folder". It gives a possibility to squeeze steps into one group. If you click at that step, the designer will show only children in that group. Of course you can place a folder into another folder.

Does that address your problem in any way?

<img width="1062" alt="Screenshot 2022-12-23 at 00 00 03" src="https://user-images.githubusercontent.com/12797776/209239466-5ed63c7b-10d1-43ff-874c-04712fb4c069.png">

**Comment by thcristianno** [comment]
Hello @b4rtaz!
Thanks for the reply!
Yes, that would solve my problem.

Do you have a timeline for releasing this feature?

**Comment by b4rtaz** [comment]
It's nice to hear that. It could take 2-3 weeks from now (that feature will be a part of [the pro version](https://github.com/nocode-js/sequential-workflow-designer-pro-demo)).

**Comment by b4rtaz** [comment]
The `folder` component is just released. Here's an [example](https://nocode-js.github.io/sequential-workflow-designer-pro-demo/examples/webpack/public/folders.html). It's available only in the pro version.
