### ISSUE TITLE
Copy/Paste for steps

### ISSUE THREAD

**Issue by tskomudek** [nocode-js/sequential-workflow-designer#80]
Hi,
it would be nice to be able to reuse an already configured step in a different 
place in the same flow.
This could be either a copy/paste action or something like <ctrl>/drag.
It'll also be useful to have like an onDuplicate callback for steps to be able to
e.g. make copies of child steps if the copied one is a container or switch.
Are there any plans to support this ?

Thank you and great job btw.
Tilo

**Comment by b4rtaz** [comment]
Hello @tskomudek,

the designer supports the duplication feature already. To turn on it you need to set a callback for the `isDuplicable` property in the configuration. Check [this article](https://nocode-js.com/docs/sequential-workflow-designer/features/editing-restrictions#is-step-duplicable). The duplication uses a deep copy, so all children should be duplicated. Check [this example](https://nocode-js.github.io/sequential-workflow-designer/examples/fullscreen.html).

>  This could be either a copy/paste action or something like /drag.

The copy/paste feature is planned. If you want to speed up the implementation, please [contact us](https://nocode-js.com/sequential-workflow-designer-pro-pricing#consulting).

**Comment by tskomudek** [comment]
Hi Bart,
that's great and exactly what i needed.
Thank you
T.
