### ISSUE TITLE
 Svelte Support for Sequential Workflow Designer

### ISSUE THREAD

**Issue by mikiastilahun** [nocode-js/sequential-workflow-designer#86]
Hello,

I appreciate the work on sequential-workflow-designer. It's been great for React and Angular projects. Given Svelte's growing popularity, it would be beneficial to have similar support for it.

If direct Svelte support is in the pipeline, could you guide us on integrating the JavaScript version into Svelte projects in the meantime?

Thank you for considering this. Looking forward to future updates!

**Comment by b4rtaz** [comment]
Hello @mikiastilahun!

Yes, Svelte is in our plans. If you want to prioritize it, please [contact us](https://nocode-js.com/contact).

> If direct Svelte support is in the pipeline, could you guide us on integrating the JavaScript version into Svelte projects in the meantime?

The sequential workflow designer can be used in any TypeScript and JavaScript project. So basically you should add the `sequential-workflow-designer` dependency to your project and you need to adapt the component to Svelte framework.

**Comment by b4rtaz** [comment]
Hello @mikiastilahun!

We've just released the 0.16.6 version with Svelte support. https://github.com/nocode-js/sequential-workflow-designer/releases/tag/v0.16.6

**Comment by mikiastilahun** [comment]
Hello @b4rtaz 

Thanks for the update. 
I'll check it out as soon as possible.
