### ISSUE TITLE
Backspace key delete step

### ISSUE THREAD

**Issue by pdolce13** [nocode-js/sequential-workflow-designer#98]
I have a **custom input** (_a div editable_) in a step when i try to delete the content od this with the backspace key, this delete te entry step.

**Note:** I use a div editable because it allow to set style to variable.
![tag_input](https://github.com/nocode-js/sequential-workflow-designer/assets/138025056/13e39eb0-e870-44df-aa0b-75a35be33fd9)

**Comment by b4rtaz** [comment]
Hello @pdolce13!

I've just released the 0.16.9 version. Now it's possible to filter keyboard events. Please check this article: https://nocode-js.com/docs/sequential-workflow-designer/features/keyboard-shortcuts
